### ISSUE TITLE
Issue with event queue

### ISSUE THREAD

**Issue by pavlem** [banjun/ReactiveSSE#4]
Hello, 
I implemented your library but I do not get all of the events from my SSE server (for example server sent 50 events, but I got only 17). Then, when a new event is sent from the server automatically I still get nothing on iOS until I force manually something new on the server then I get the previous one on iOS that was sent automatically. Like there is some queue in your library which caught it but is not displaying it in the Result <SSEvent, SSError>. We deduced that it's always one behind. 

Is it possible that there is some queue in your library with some max value or some setting that I am unaware of?

**Comment by tarag** [comment]
Hello,

Check the other issue I opened, it is exactly what you are talking about.

There is a PR with a correction.

**Comment by banjun** [comment]
Thank you reporting. I agree with @tarag. duplicates #2
